---
abstract: 'Perl to HiveServer2 Thrift API wrapper'
author:
  - 'David Morel <david.morel@amakuru.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Thrift-API-HiveClient2
requires:
  Class::Accessor: 0
  Moo: 0
  Thrift: 0
version: 0.013
